//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YetAnotherRelogger.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseToTray {
            get {
                return ((bool)(this["CloseToTray"]));
            }
            set {
                this["CloseToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowNotification {
            get {
                return ((bool)(this["ShowNotification"]));
            }
            set {
                this["ShowNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinimizeToTray {
            get {
                return ((bool)(this["MinimizeToTray"]));
            }
            set {
                this["MinimizeToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysShowTray {
            get {
                return ((bool)(this["AlwaysShowTray"]));
            }
            set {
                this["AlwaysShowTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseD3Starter {
            get {
                return ((bool)(this["UseD3Starter"]));
            }
            set {
                this["UseD3Starter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string D3StarterPath {
            get {
                return ((string)(this["D3StarterPath"]));
            }
            set {
                this["D3StarterPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseAutoPos {
            get {
                return ((bool)(this["UseAutoPos"]));
            }
            set {
                this["UseAutoPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForceAutoPos {
            get {
                return ((bool)(this["ForceAutoPos"]));
            }
            set {
                this["ForceAutoPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoPosDiabloCascade {
            get {
                return ((bool)(this["AutoPosDiabloCascade"]));
            }
            set {
                this["AutoPosDiabloCascade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoPosDemonbuddyCascade {
            get {
                return ((bool)(this["AutoPosDemonbuddyCascade"]));
            }
            set {
                this["AutoPosDemonbuddyCascade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal AutoPosDiabloStartX {
            get {
                return ((decimal)(this["AutoPosDiabloStartX"]));
            }
            set {
                this["AutoPosDiabloStartX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal AutoPosDiabloStartY {
            get {
                return ((decimal)(this["AutoPosDiabloStartY"]));
            }
            set {
                this["AutoPosDiabloStartY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("320")]
        public decimal AutoPosDiabloW {
            get {
                return ((decimal)(this["AutoPosDiabloW"]));
            }
            set {
                this["AutoPosDiabloW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public decimal AutoPosDiabloH {
            get {
                return ((decimal)(this["AutoPosDiabloH"]));
            }
            set {
                this["AutoPosDiabloH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal AutoPosDemonbuddyStartX {
            get {
                return ((decimal)(this["AutoPosDemonbuddyStartX"]));
            }
            set {
                this["AutoPosDemonbuddyStartX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal AutoPosDemonbuddyStartY {
            get {
                return ((decimal)(this["AutoPosDemonbuddyStartY"]));
            }
            set {
                this["AutoPosDemonbuddyStartY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("320")]
        public decimal AutoPosDemonbuddyW {
            get {
                return ((decimal)(this["AutoPosDemonbuddyW"]));
            }
            set {
                this["AutoPosDemonbuddyW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public decimal AutoPosDemonbuddyH {
            get {
                return ((decimal)(this["AutoPosDemonbuddyH"]));
            }
            set {
                this["AutoPosDemonbuddyH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("right")]
        public string AutoPosDemonbuddyPos {
            get {
                return ((string)(this["AutoPosDemonbuddyPos"]));
            }
            set {
                this["AutoPosDemonbuddyPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoPosForceWorkingArea {
            get {
                return ((bool)(this["AutoPosForceWorkingArea"]));
            }
            set {
                this["AutoPosForceWorkingArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal AutoPosForceWorkingAreaX {
            get {
                return ((decimal)(this["AutoPosForceWorkingAreaX"]));
            }
            set {
                this["AutoPosForceWorkingAreaX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal AutoPosForceWorkingAreaY {
            get {
                return ((decimal)(this["AutoPosForceWorkingAreaY"]));
            }
            set {
                this["AutoPosForceWorkingAreaY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("320")]
        public decimal AutoPosForceWorkingAreaW {
            get {
                return ((decimal)(this["AutoPosForceWorkingAreaW"]));
            }
            set {
                this["AutoPosForceWorkingAreaW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public decimal AutoPosForceWorkingAreaH {
            get {
                return ((decimal)(this["AutoPosForceWorkingAreaH"]));
            }
            set {
                this["AutoPosForceWorkingAreaH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ISBoxerPath {
            get {
                return ((string)(this["ISBoxerPath"]));
            }
            set {
                this["ISBoxerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConnectionCheckPing {
            get {
                return ((bool)(this["ConnectionCheckPing"]));
            }
            set {
                this["ConnectionCheckPing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.google.com")]
        public string ConnectionCheckPingHost1 {
            get {
                return ((string)(this["ConnectionCheckPingHost1"]));
            }
            set {
                this["ConnectionCheckPingHost1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.pingtest.com")]
        public string ConnectionCheckPingHost2 {
            get {
                return ((string)(this["ConnectionCheckPingHost2"]));
            }
            set {
                this["ConnectionCheckPingHost2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConnectionCheckCloseBots {
            get {
                return ((bool)(this["ConnectionCheckCloseBots"]));
            }
            set {
                this["ConnectionCheckCloseBots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FocusCheck {
            get {
                return ((bool)(this["FocusCheck"]));
            }
            set {
                this["FocusCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConnectionCheckIpHost {
            get {
                return ((bool)(this["ConnectionCheckIpHost"]));
            }
            set {
                this["ConnectionCheckIpHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConnectionCheckIpHostCloseBots {
            get {
                return ((bool)(this["ConnectionCheckIpHostCloseBots"]));
            }
            set {
                this["ConnectionCheckIpHostCloseBots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConnectionCheckIpCheck {
            get {
                return ((bool)(this["ConnectionCheckIpCheck"]));
            }
            set {
                this["ConnectionCheckIpCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConnectionCheckHostCheck {
            get {
                return ((bool)(this["ConnectionCheckHostCheck"]));
            }
            set {
                this["ConnectionCheckHostCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnectionCheckIpHostList {
            get {
                return ((string)(this["ConnectionCheckIpHostList"]));
            }
            set {
                this["ConnectionCheckIpHostList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal DemonbuddyStartDelay {
            get {
                return ((decimal)(this["DemonbuddyStartDelay"]));
            }
            set {
                this["DemonbuddyStartDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoPosDiabloNoFrame {
            get {
                return ((bool)(this["AutoPosDiabloNoFrame"]));
            }
            set {
                this["AutoPosDiabloNoFrame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public decimal GoldTimer {
            get {
                return ((decimal)(this["GoldTimer"]));
            }
            set {
                this["GoldTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseGoldTimer {
            get {
                return ((bool)(this["UseGoldTimer"]));
            }
            set {
                this["UseGoldTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartWithWindows {
            get {
                return ((bool)(this["StartWithWindows"]));
            }
            set {
                this["StartWithWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal StartDelay {
            get {
                return ((decimal)(this["StartDelay"]));
            }
            set {
                this["StartDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinimizeOnStart {
            get {
                return ((bool)(this["MinimizeOnStart"]));
            }
            set {
                this["MinimizeOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Location {
            get {
                return ((string)(this["Location"]));
            }
            set {
                this["Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public decimal DiabloStartTimeLimit {
            get {
                return ((decimal)(this["DiabloStartTimeLimit"]));
            }
            set {
                this["DiabloStartTimeLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseKickstart {
            get {
                return ((bool)(this["UseKickstart"]));
            }
            set {
                this["UseKickstart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal KickstartDelay {
            get {
                return ((decimal)(this["KickstartDelay"]));
            }
            set {
                this["KickstartDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KickstartAlwaysGenerateNew {
            get {
                return ((bool)(this["KickstartAlwaysGenerateNew"]));
            }
            set {
                this["KickstartAlwaysGenerateNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GoldInfoLogging {
            get {
                return ((bool)(this["GoldInfoLogging"]));
            }
            set {
                this["GoldInfoLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal StatsUpdateRate {
            get {
                return ((decimal)(this["StatsUpdateRate"]));
            }
            set {
                this["StatsUpdateRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public decimal StatsCPUHistory {
            get {
                return ((decimal)(this["StatsCPUHistory"]));
            }
            set {
                this["StatsCPUHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public decimal StatsMemoryHistory {
            get {
                return ((decimal)(this["StatsMemoryHistory"]));
            }
            set {
                this["StatsMemoryHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public decimal StatsGphHistory {
            get {
                return ((decimal)(this["StatsGphHistory"]));
            }
            set {
                this["StatsGphHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public decimal StatsGoldPrice {
            get {
                return ((decimal)(this["StatsGoldPrice"]));
            }
            set {
                this["StatsGoldPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public decimal StatsConnectionsHistory {
            get {
                return ((decimal)(this["StatsConnectionsHistory"]));
            }
            set {
                this["StatsConnectionsHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StatsEnabled {
            get {
                return ((bool)(this["StatsEnabled"]));
            }
            set {
                this["StatsEnabled"] = value;
            }
        }
    }
}
